import type { Todo } from "../types/common/Todo";

export const todos: Todo[] = [
  {
    title: "Move in together",
    description:
      "Move into a apartment that comes with a garage or ev charging",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Build a gingerbread house together",
    description: "Create a cozy gingerbread house during the holidays",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Aquarium dates",
    description:
      "Visit the local aquarium and enjoy a day surrounded by marine life",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Go to concerts",
    description: "Ed Sheeran, The Marias, Coldplay, etc.",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Stargazing nights",
    description: "ideally in a campsite while we can cook some camp food",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Go hiking or camping",
    description: "with professional gear and backpacks",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Try kayaking",
    description: "in a scenic location",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Try jetskiing",
    description: "hopefully when we are on a trip to a beach destination",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Try skiing or snowboarding",
    description: "hit the slopes together",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Go scuba diving",
    description: "take a selfie together underwater",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Take a hot air balloon ride",
    description: "this is a big one!",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Go on a cruise",
    description: "a caribbean cruise would be amazing",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Finish the house puzzle we bought",
    description: "leo will be of no use but it's ok",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Adopt a shiba (maybe towards year 5)",
    description: "and snuggle with it and Lucky",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Travel to China and the Philippines",
    description: "try a ton of street stalls and massage services",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Hawaii trip",
    description: "seafood, beaches, and volcanoes",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "See the Northern Lights (big trip / maybe year 5)",
    description: "lets go to Alaska or Iceland",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Make photo album of our adventures",
    description: "collect all our favorite photos and memories",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Workout together (consistently)",
    description: "leo will be the trainer and maria will do meal prep",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Get a house together (ok if not in 5 years)",
    description: "preferably with a second or third floor",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Keep planning and saving for future trips",
    description:
      "always prioritize living to the fullest not for material things",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Continue supporting each other’s dreams and goals",
    description: "be each other's biggest cheerleaders",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
  {
    title: "Be genuinely happy and content while dreaming of what’s next",
    description: "appreciate the present while planning for the future",
    createdAt: new Date().toISOString(),
    createdBy: "maria",
    status: { leo: false, maria: false },
  },
];
